/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ILimitOrderFiller,
  ILimitOrderFillerInterface,
} from "../../../contracts/core/ILimitOrderFiller";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_orderId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_tokenIn",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amountIn",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_params",
        type: "bytes",
      },
    ],
    name: "executeOperation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ILimitOrderFiller__factory {
  static readonly abi = _abi;
  static createInterface(): ILimitOrderFillerInterface {
    return new utils.Interface(_abi) as ILimitOrderFillerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILimitOrderFiller {
    return new Contract(address, _abi, signerOrProvider) as ILimitOrderFiller;
  }
}
